#ifndef __BENJI_ERROR_H
#define __BENJI_ERROR_H

#ifndef BENJI_ERROR_NONE
    #define BENJI_ERROR_NONE (0)
#endif

#ifndef BENJI_ERROR_UNKNOWN_COMMAND
    #define BENJI_ERROR_UNKNOWN_COMMAND (-1)
#endif

#ifndef BENJI_ERROR_INSUFFICIENT_ARGUMENT_COUNT
    #define BENJI_ERROR_INSUFFICIENT_ARGUMENT_COUNT (-2)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_OPEN_SC_MANAGER
    #define BENJI_ERROR_UNABLE_TO_OPEN_SC_MANAGER (-3)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_OPEN_SERVICE
    #define BENJI_ERROR_UNABLE_TO_OPEN_SERVICE (-4)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_CREATE_SERVICE
    #define BENJI_ERROR_UNABLE_TO_CREATE_SERVICE (-5)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_START_SERVICE
    #define BENJI_ERROR_UNABLE_TO_START_SERVICE (-6)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_DELETE_SERVICE
    #define BENJI_ERROR_UNABLE_TO_DELETE_SERVICE (-7)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_CREATE_REGISTRY_KEY
    #define BENJI_ERROR_UNABLE_TO_CREATE_REGISTRY_KEY (-8)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_SET_REGISTRY_KEY_VALUE
    #define BENJI_ERROR_UNABLE_TO_SET_REGISTRY_KEY_VALUE (-9)
#endif

#endif