#ifndef __BENJI_ERROR_H
#define __BENJI_ERROR_H

#ifndef BENJI_ERROR_UNABLE_TO_OPEN_SC_MANAGER
    #define BENJI_ERROR_UNABLE_TO_OPEN_SC_MANAGER (-1)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_CREATE_SERVICE
    #define BENJI_ERROR_UNABLE_TO_CREATE_SERVICE (-2)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_DELETE_SERVICE
    #define BENJI_ERROR_UNABLE_TO_DELETE_SERVICE (-3)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_START_SERVICE
    #define BENJI_ERROR_UNABLE_TO_START_SERVICE (-4)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_OPEN_SERVICE
    #define BENJI_ERROR_UNABLE_TO_OPEN_SERVICE (-5)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_CREATE_REGISTRY_KEY
    #define BENJI_ERROR_UNABLE_TO_CREATE_REGISTRY_KEY (-6)
#endif

#ifndef BENJI_ERROR_UNABLE_TO_SET_REGISTRY_KEY_VALUE
    #define BENJI_ERROR_UNABLE_TO_SET_REGISTRY_KEY_VALUE (-7)
#endif

#endif